channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
      - mlflow
      - cloudpickle
      - numpy
      - pandas
      - psutil
      - scikit-learn
      - scipy
      - seaborn
      - xgboost
      - lightgbm
      - dagshub
name: depression_env