channels:
- conda-forge
dependencies:
- python=3.8
- pip
- pip:
  - mlflow
  - cloudpickle
  - numpy
  - pandas
  - psutil
  - scikit-learn
  - scipy
  - xgboost
  - lightgbm
  - dagshub
name: depression_env