name: depression_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - pandas
      - scikit-learn
      - mlflow
      - xgboost
      - lightgbm
      - dagshub
      - numpy