name: Train Model Workflow

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: depression_env
          environment-file: MLProject/conda.yaml
          use-mamba: true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run model training with mlflow run
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate depression_env
          export MLFLOW_TRACKING_URI=http://127.0.0.1:5000
          mlflow run ./MLProject --P data_path=student-depression-dataset_preprocessing.csv

      - name: Get latest run ID
        id: get_run_id
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate depression_env
          EXPERIMENT_ID=$(mlflow experiments list | grep Model_Training_Default_Parameters | awk '{print $1}')
          RUN_ID=$(mlflow runs list --experiment-id $EXPERIMENT_ID --max-results 1 --order-by attribute.start_time DESC --output json | jq -r '.[0].run_id')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Generate Dockerfile for serving model
        run: |
          mkdir -p docker_serving
          mlflow models generate-dockerfile -m runs:/${{ steps.get_run_id.outputs.run_id }}/model -n student_depression_model -d docker_serving

      - name: Setup Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Git LFS track
        run: git lfs track "mlruns/**/model.pkl"

      - name: Commit and push mlruns folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git add mlruns
          git commit -m "Save mlruns from CI run" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push MLflow model Docker image
        run: |
          cd docker_serving
          docker build -t student-depression-model .
          docker push student-depression-model