name: Train Model Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: depression_env
          environment-file: MLProject/conda.yaml
          use-mamba: true
      - name: Run MLflow Project training
        shell: bash
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate depression_env
          mlflow run MLProject -P data_path=student-depression-dataset_preprocessing.csv