name: Train Model Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: depression_env
          environment-file: MLProject/conda.yaml
          use-mamba: true

      - name: Run model training with local MLflow
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate depression_env
          python MLProject/modelling.py --data_path MLProject/student-depression-dataset_preprocessing.csv

      - name: Commit and push mlruns folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git add mlruns
          git commit -m "Save mlruns from CI run" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}



      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t rendika7/student-depression-model:latest .
          docker push rendika7/student-depression-model:latest